CommandStatsDisplaySkullSkin: false
DecimalFormat: '#.##'
Compatibility:
  MythicMobs: true # 穿戴和掉落物品目前与SX-Item有一定冲突, 如果物品ID相同, 会判断两次. 可选择性关闭SX的掉落/穿戴功能, 重启有效
Holographic:
  Enabled: true
  DisplayTime: 2
  HealthOrTake:
    Enabled: false
HealthDisplays:
  Name:
    Enabled: true
    Size: 10
    Current: ❤
    Loss: '&7❤'
    Prefix: '&8[&c'
    Suffix: '&8] &7- &8[&c{0}&8]'
    DisplayTime: 4
  BossBar:
    Enabled: true
    Format: '&a&l{0}:&8&l[&a&l{1}&7&l/&c&l{2}&8&l]'
    DisplayTime: 4
    BlackCauseList:
    - CUSTOM
ItemDisplayName: true
DamageEvent:
  Priority: HIGH
  BlackCauseList:
  - CUSTOM
  DamageCalculationToEVE: false
  DamageGauges: true
  BanShieldDefense: false
  BowCloseRangeAttack: false
  MinimumDamage: 1.0
ClearDefaultAttribute: true
RPGInventorySlot:
- 4
- 10
- 13
- 14
- 19
- 22
- 28
- 31
- 47
- 48
- 49
- 50
- 51
RepairItemValue: 3.5
RegisterSlots:
  Enabled: true
  List:
  - 17#宝藏
  - 26#戒指
  - 35#项链
DefaultAttribute:
- '生命上限: 20'
Condition:
  Hand:
    MainName: 主武器
    OffName: 副武器
  Armor:
  - 头盔
  - 盔甲
  - 护腿
  - 靴子
  Role:
    Name: 限制职业
  LimitLevel:
    Name: 限制等级
  Durability:
    Name: 耐久度
    ClearItem: false
  Sell:
    Name: 出售价格
  ExpiryTime:
    Name: 到期时间
    Format: yyyy/MM/dd HH:mm
AttributePriority:
- JSAttribute
- Dodge#SX-Attribute
- Damage
- Crit
- Real
- Defense
- Reflection
- Block
- LifeSteal
- Ignition
- AttackPotion
- Lightning
- Tearing
- Toughness
- Health
- HealthRegen
- HitRate
- ExpAddition
- Command
- WalkSpeed
- AttackSpeed
- MythicMobsDrop
- EventMessage
ConditionPriority:
- Hand
- MainHand
- OffHand
- LimitLevel
- Role
- ExpiryTime
- Durability