name: SX-Attribute
main: github.saukiya.sxattribute.SXAttribute
version: $version
author: Saukiya
api-version: 1.13

depend:
  - SX-Item

softdepend:
- HolographicDisplays
- PlaceholderAPI
- RPGInventory
- MythicMobs
- SkillAPI
- Vault

commands:
  sxAttribute:
    aliases: [ sx, sa, sxa ]

permissions:
  sx-attribute.use:
    default: true
  sx-attribute.stats:
    default: true