name: SX-Attribute
main: github.saukiya.sxattribute.SXAttribute
version: $version
author: Saukiya & Ray_Hughes
api-version: 1.13

depend:
- SX-Item

libraries:
- org.openjdk.nashorn:nashorn-core:15.3

softdepend:
- HolographicDisplays
- PlaceholderAPI
- RPGInventory
- MythicMobs
- SkillAPI
- Vault

commands:
  SxAttribute:
    aliases:
    - sx

permissions:
  sx-attribute.use:
    default: true
  sx-attribute.stats:
    default: true
