Default-1:
  Name: <s:DefaultPrefix>&c炎之洗礼<s:DefaultSuffix> <s:<l:品质>Color><l:品质>
  ID:
  - <s:<l:职业>ID>
  Lore:
  - '&6品质等级: <s:<l:品质>Color><l:品质>'
  - '<s:<l:品质>职判>&6限制职业: <l:职业>'
  - '&6物品类型: 主武器'
  - '&6限制等级: <c:int 10 * <s:<l:品质>基数>>级'
  - '&c攻击力: +<c:20 * <s:<l:品质>基数>>'
  - <s:攻一-10>
  - <s:攻二-10>
  - <s:攻三-10>
  - <l:材质>
  - <s:<l:品质>宝石孔>
  - '&7耐久度: <c:int <r:300_350> * <s:<l:品质>基数>>/<c:int 400 * <s:<l:品质>基数>>'
  - <s:<l:品质>绑判>&c已绑定
  - '&a到期时间: <t:600>'
  - '<s:<l:品质>介判>                                    '
  - <s:<l:品质>介判><s:DefaultLore>
  EnchantList:
  - <s:<l:职业>附魔>
  ItemFlagList:
  - HIDE_ATTRIBUTES
  Unbreakable: false
Default-2:
  Name: '&c机械轻羽之靴'
  ID: 301
  Lore:
  - '&6物品类型: 靴子'
  - '&c生命上限: +2000'
  - '&d移速增幅: +50%'
  - '&6限制等级: <r:50_100>级'
  - '&r'
  - '&8速度 II'
  - '&c支持单项自动更新-(自动更新)'
  - '&c支持单项关闭清除标签'
  - '&r'
  - '&e出售价格: 250'
  EnchantList:
  - DURABILITY:1
  ItemFlagList:
  - HIDE_ENCHANTS
  - HIDE_UNBREAKABLE
  Unbreakable: true
  Color: ffffff
  Update: true
  ClearAttribute: false
Default-3:
  Name: '&b雷霆领主项链'
  ID: 287
  Lore:
  - '&6物品类型: 项链'
  - '&c生命上限: +200'
  - '&d移速增幅: +50%'
  - '&d雷霆几率: +20%'
  - '&6限制等级: <r:20_30>级'
  - '&r'
  - '&e出售价格: 500'
  - '&r'
  - '&8&o拥有着驾驭飞行的能力'
  - '&8&o"放在背包第三行最后一格生效"'
  EnchantList:
  - DURABILITY:1
Default-4:
  Type: Import
  Item:
    ==: org.bukkit.inventory.ItemStack
    type: APPLE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      lore:
      - §7一个Type类型为 Import 的物品
      - ''
      - §c如何保存这种类型的物品?§7
      - ''
      - §7/sx save 编号 Import
      - ''
      - §c它不支持自动更新§7
Default-5:
  Name: '&b慢剑'
  ID: 267
  Lore:
  - '&7设置物品默认攻速，与玩家自身属性分离'
  - '&7物品攻速最低为0-最高为4'
  - '&7AttackSpeed.yml文件内可设置玩家默认攻速'
  - '&7以及各工具默认攻速'
  - ''
  - '&c若玩家攻速+物品攻速小于等于4'
  - '&c工具将无法抬起'
  Type: SX
  AttackSpeed: 0.8
Default-6:
  Name: '&c&l鸽子肉'
  ID: '351:7'
  Lore:
  - ''
  - '&6物品类型: 宝藏'
  - ''
  - '&b连肉都散发出了耀眼光芒'
  - ''
  - '&8&o"放在背包第一行最后一格生效"'
  EnchantList:
  - DURABILITY:1
  ItemFlagList:
  - HIDE_ENCHANTS
